create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  topic text not null,
  text text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array'),
  correct_index integer not null check (correct_index >= 0),
  explanation text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists questions_active_sort_order_idx
  on public.questions (active, sort_order, id);

alter table public.questions enable row level security;

drop policy if exists "Public read active questions" on public.questions;
create policy "Public read active questions"
  on public.questions
  for select
  using (active = true);
